# Generated by Django 4.2.30 on 2026-10-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_booking_mechanic_name_mediaattachment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='client_token',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
